### ISSUE TITLE
PHP8 fixes for "Fatal error: Uncaught ValueError: Unknown format specifier"

### ISSUE THREAD

**Issue by benjamincaramatie** [wp-property/wp-property#633]
Hi,

Here is a fix to solve the PHP8 compatibility issue that the plugin currently has.

### Issue

When activated on a PHP8 server, WP-Property plugin creates a fatal error.
When wp-debug is activated, it returns the following message:

`Fatal error: Uncaught ValueError: Unknown format specifier "t" in /www/wp-content/plugins/wp-property/l10n.php:50 Stack trace: #0 /www/wp-content/plugins/wp-property/l10n.php(50): sprintf('Showing % to % ...', '0', '0', '0') #1 /www/wp-content/plugins/wp-property/lib/class_core.php(1356): include('/...') #2 /www/wp-content/plugins/wp-property/lib/class_core.php(306): WPP_Core->get_l10n_data() #3 /www/wp-includes/class-wp-hook.php(303): WPP_Core->init_lower('') #4 /www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #5 /www/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #6 /www/wp-settings.php(578): do_action('init') #7 /www/wp-config.php(79): require_once('/...') #8 /www/wp-load.php(50): require_once('/...') #9 /www/wp-blog-header.php(13): require_once('/...') #10 /www/index.php(17): require('/...') #11 {main} thrown in /www/wp-content/plugins/wp-property/l10n.php on line 50
`

### Fix

This issue is caused by an error in the **l10n.php** file (in wp-property root folder), on line 50.

_Original code:_
`'showing_entries_null'          => sprintf( __( 'Showing % to % of % entries', ud_get_wp_property()->domain ), '0', '0', '0' ),
`

_Fixed code:_
`'showing_entries_null'          => sprintf( __( 'Showing %s to %s of %s entries', ud_get_wp_property()->domain ), '0', '0', '0' ),
`

### Additional fix

In the **/lib/class_functions.php** file, the curly braces **{ }** need to be replaced by square brackets **[ ]**, as curly braces have been deprecated in PHP8.

_Original code:_
`      $current = ord($value{$i});`

_Fixed code:_
`      $current = ord($value[$i]);`

**Comment by DavidTheWebDev** [comment]
Just inherited a website that uses this, thanks!
